language: node_js
node_js:
  - "stable"
cache:
  directories:
    - ~/.npm
    - ~/.cache
install:
  - yarn install --frozen-lockfile
script:
  - npm test
  - npm run build
  - npm run cy:test
on:
  branch: master
