language: node_js
node_js:
  - "10"
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  directories:
    - ~/.npm
    - ~/.cache
install:
  - yarn install --frozen-lockfile
  - cd functions && yarn install --frozen-lockfile && cd ..
jobs:
  include:
    - stage: unit tests
      script:
        - npm test
        - npm run codecov
    - stage: integration tests
      script:
        - npm run build
        - npm run cy:test
    - stage: deploy to staging
      script: npm run build
      deploy:
        provider: firebase
        project: "odch-aircraft-logbook-dev"
        token:
          secure: RPdXFWvRaq1uT13AAkVj2mktUwLgYLoJ1QBhroQKfZJHE567O20WxjY5jCXb53FSs1oGQyK7ZJePpKLrMQedP06tBsAzzGtW+tuKhRHEDNEE5HDweTJD186UUwj3mLJAOXIl8ZZZDe5U7sv7Z+mWdUXxQtevRmpj+0nRdanvIFB3ApCsIzHe1cj8SevyOk82pH84tDCvqFHcFNnuzNUFvfJdJGAPUWvhln5rLiel/CQBXK7vXEMW97LZ29QfGn5xRFshrqPxr6Zk6/0iE+oMqKv24pUw2yJwVIAr0QDcuTY0sNIzjVb427m5c1scLDYEX5XzCyeLgWl3nLcnIN4QlJtJb4hBTpeDd5j2EQWcrUsL5Qhc1vzwDz4w+wLdbXCIa1o3sZqS4npK2IqduPUWtVVEGmnjFMa6PIGR8F6K4NiixJ9G1PubPyz1kM8hkjxOqGTdYZNR0Zfx9ywLX8Fj7NKqfjhNxJWuZwwtbjTuta9xmuEdgoVGMeGXT5R6BPQT4ptJKW4wFdp/hoB2Gzqr3jHeOcSZRpoETIwHfN5d4D6/JB6WHlR6lieoYOFxRjbexfvjRkleYKCe210wfhcgWofgQfmrF9glwwOFREWID5N7/XZ1TRVlqm+27xZ165EUqO6HPYu9OiDG6wR9YTl4Ofst54IDX++NzMP5qS/x6IU=
        skip_cleanup: true
        on:
          branch: develop
    - stage: deploy to production
      script: npm run build --project=prod
      deploy:
        provider: firebase
        project: "odch-aircraft-logbook-prod"
        token:
          secure: XZar5Ak6y60aOkM/ltq6jpiM9SZO1IrXqqHpox1VEt0tQMHupj78WGRGeZuP17l6XfaRWxPXEiVdycbftMTy3hmHwX6zd5yvzL9qCF/RozzGcPiGrr0Gy9eyM0kdqOoS5SAgC7JD46JZ+N447NUJEhcrETsTRt2fMSVe6BULNe8igVMl0IykaB0a+KQJPoLPBhWHksc4szBhcjEJ6LuQVeScBcPYNEAsM1f6Jw2zmfV3ctQz7htAh+7Z9NWgqasD2ULD+TNkh/oxqL4SXE7VOpvKNMixZ0sbnnQHGlrUW/fcncW9fK6oJbKrktui3VwK6zghEkPNaFTNl4Wka/4jpczhKgcyC6IhqxA7zOUNqMNkl+n04x58Pt4ugVDEdWeeMq+bmhGjShTJ+3xosb80ewa5jjwEvlYtrdWl0pYK/GQ9iSyG38Wl/wNcrJJgb3iptqZQuspRXY9weNgVpIV5tFfr32QCAkMJ+qSTDf/1nnUihhztdWEiXxQjyOWX5BUBRdbrgRVkyeuTC7hgTKuj8S3TCdK4rdVltw9r8l9ZeGAs9qRJsaQU9BKGeyFMEAZ/C53ev1SpB6hdX/hNIq8d0t85SJF391jBwPY2q9sg5aYj7G+z6zTa21Al1+hFHggihBo9/uY/WxjHvDGMpKBs/0BqGCdr7S6DrQqWsEBWWLE=
        skip_cleanup: true
        on:
          branch: master
